// <auto-generated />
namespace Bank.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FithMigrationBank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FithMigrationBank));
        
        string IMigrationMetadata.Id
        {
            get { return "201912071842367_FithMigrationBank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
